### ISSUE TITLE
launch checklist

### ISSUE THREAD

**Issue by ssupix** [ssupix/mariasupix.com#13]
**Browser support:**

- [x]  Responsive in all viewports
- [x]  Chrome
- [x]  Safari
- [x]  Edge
- [x]  FireFox

**Devices:**

- [x]  Mobile IOS
- [x]  Mobile Android
- [x]  Tablet IOS
- [x]  Laptop
- [x]  Desktop

**Code & Optimization**

- [x]  Custom Error Pages
- [x]  All images have ALT text
- [x]  All videos have same attributes “playsinline loop autoplay muted”
- [x]  All the videos have titles and posters
- [x]  All images under 1MB
- [x]  All videos are optimized to the smallest possible size
- [x]  Developer console is free of errors from local scripts
- [x]  CSS & JS minfied

**Content**

- [x]  No spelling mistakes
- [x]  Each artifact linked properly
- [x]  All accessible pages are 100% complete.

**SEO**

- [x]  OG tags are specific to each page
- [x]  Metadata is specific to each page
- [x]  Fav Icon works on all of the pages
